# Generated by Django 6.0.7 on 2026-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(max_length=100)),
                ('status', models.CharField(default='Offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
