# Generated by Django 6.0.7 on 2026-07-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('raw_data', models.JSONField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.systemagent')),
            ],
        ),
    ]
