# Generated by Django 6.0.2 on 2026-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
